/*
 * generated by Xtext 2.17.1
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.UpctformaGrammarAccess;

@SuppressWarnings("all")
public class UpctformaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected UpctformaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Literal_Number_Text___IntKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___LiteralKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___TextKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UpctformaGrammarAccess) access;
		match_Literal_Number_Text___IntKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___LiteralKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___TextKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLiteralAccess().getLiteralKeyword_0()), new TokenAlias(false, false, grammarAccess.getLiteralAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getLiteralAccess().getRightCurlyBracketKeyword_3())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getNumberAccess().getIntKeyword_0()), new TokenAlias(false, false, grammarAccess.getNumberAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getNumberAccess().getRightCurlyBracketKeyword_3())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTextAccess().getTextKeyword_0()), new TokenAlias(false, false, grammarAccess.getTextAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getTextAccess().getRightCurlyBracketKeyword_3())));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Literal_Number_Text___IntKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___LiteralKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___TextKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__.equals(syntax))
				emit_Literal_Number_Text___IntKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___LiteralKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___TextKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('Text' '{' '}') | ('Int' '{' '}') | ('Literal' '{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Literal_Number_Text___IntKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___LiteralKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___TextKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
