/*
 * generated by Xtext 2.17.1
 */
package org.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalUpctformaParser;
import org.xtext.services.UpctformaGrammarAccess;

public class UpctformaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UpctformaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UpctformaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getContentElementAccess().getAlternatives(), "rule__ContentElement__Alternatives");
			builder.put(grammarAccess.getCompositeTypeAccess().getAlternatives(), "rule__CompositeType__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEPrimitiveTypesAccess().getAlternatives(), "rule__EPrimitiveTypes__Alternatives");
			builder.put(grammarAccess.getContentUnitTypeAccess().getAlternatives(), "rule__ContentUnitType__Alternatives");
			builder.put(grammarAccess.getSectionTypeAccess().getAlternatives(), "rule__SectionType__Alternatives");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup(), "rule__ContentDefinition__Group__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_4(), "rule__ContentDefinition__Group_4__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_5(), "rule__ContentDefinition__Group_5__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_5_1(), "rule__ContentDefinition__Group_5_1__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_6(), "rule__ContentDefinition__Group_6__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_6_3(), "rule__ContentDefinition__Group_6_3__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_7(), "rule__ContentDefinition__Group_7__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getGroup_7_3(), "rule__ContentDefinition__Group_7_3__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getTemplateDefAccess().getGroup(), "rule__TemplateDef__Group__0");
			builder.put(grammarAccess.getTemplateDefAccess().getGroup_4(), "rule__TemplateDef__Group_4__0");
			builder.put(grammarAccess.getTemplateDefAccess().getGroup_4_1(), "rule__TemplateDef__Group_4_1__0");
			builder.put(grammarAccess.getContentUnitAccess().getGroup(), "rule__ContentUnit__Group__0");
			builder.put(grammarAccess.getContentUnitAccess().getGroup_6(), "rule__ContentUnit__Group_6__0");
			builder.put(grammarAccess.getType_ImplAccess().getGroup(), "rule__Type_Impl__Group__0");
			builder.put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
			builder.put(grammarAccess.getRowAccess().getGroup_3(), "rule__Row__Group_3__0");
			builder.put(grammarAccess.getRowAccess().getGroup_3_1(), "rule__Row__Group_3_1__0");
			builder.put(grammarAccess.getRowAccess().getGroup_4(), "rule__Row__Group_4__0");
			builder.put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_3(), "rule__Column__Group_3__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_4(), "rule__Column__Group_4__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_4_1(), "rule__Column__Group_4_1__0");
			builder.put(grammarAccess.getUseTemplateAccess().getGroup(), "rule__UseTemplate__Group__0");
			builder.put(grammarAccess.getUseTemplateAccess().getGroup_2(), "rule__UseTemplate__Group_2__0");
			builder.put(grammarAccess.getUseTemplateAccess().getGroup_2_2(), "rule__UseTemplate__Group_2_2__0");
			builder.put(grammarAccess.getContentElement_ImplAccess().getGroup(), "rule__ContentElement_Impl__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3(), "rule__Image__Group_3__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup(), "rule__Widget__Group__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup_4(), "rule__Widget__Group_4__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup_4_2(), "rule__Widget__Group_4_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
			builder.put(grammarAccess.getTextAccess().getGroup_2(), "rule__Text__Group_2__0");
			builder.put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
			builder.put(grammarAccess.getLiteralAccess().getGroup(), "rule__Literal__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getComposite_ImplAccess().getGroup(), "rule__Composite_Impl__Group__0");
			builder.put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_3(), "rule__Video__Group_3__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_5(), "rule__Video__Group_5__0");
			builder.put(grammarAccess.getSimpleElement_ImplAccess().getGroup(), "rule__SimpleElement_Impl__Group__0");
			builder.put(grammarAccess.getPlaceHolderAccess().getGroup(), "rule__PlaceHolder__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup(), "rule__Game__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup_3(), "rule__Game__Group_3__0");
			builder.put(grammarAccess.getFieldValueAccess().getGroup(), "rule__FieldValue__Group__0");
			builder.put(grammarAccess.getRecordValueAccess().getGroup(), "rule__RecordValue__Group__0");
			builder.put(grammarAccess.getRecordValueAccess().getGroup_2(), "rule__RecordValue__Group_2__0");
			builder.put(grammarAccess.getListValueAccess().getGroup(), "rule__ListValue__Group__0");
			builder.put(grammarAccess.getListValueAccess().getGroup_2(), "rule__ListValue__Group_2__0");
			builder.put(grammarAccess.getWidgetTypeAccess().getGroup(), "rule__WidgetType__Group__0");
			builder.put(grammarAccess.getWidgetTypeAccess().getGroup_5(), "rule__WidgetType__Group_5__0");
			builder.put(grammarAccess.getCompositeType_ImplAccess().getGroup(), "rule__CompositeType_Impl__Group__0");
			builder.put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_7(), "rule__Section__Group_7__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_7_1(), "rule__Section__Group_7_1__0");
			builder.put(grammarAccess.getSimpleTypeAccess().getGroup(), "rule__SimpleType__Group__0");
			builder.put(grammarAccess.getRecordTypeAccess().getGroup(), "rule__RecordType__Group__0");
			builder.put(grammarAccess.getRecordTypeAccess().getGroup_3(), "rule__RecordType__Group_3__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getListTypeAccess().getGroup(), "rule__ListType__Group__0");
			builder.put(grammarAccess.getContentDefinitionAccess().getNameAssignment_2(), "rule__ContentDefinition__NameAssignment_2");
			builder.put(grammarAccess.getContentDefinitionAccess().getNameAssignment_4_1(), "rule__ContentDefinition__NameAssignment_4_1");
			builder.put(grammarAccess.getContentDefinitionAccess().getImportsAssignment_5_0(), "rule__ContentDefinition__ImportsAssignment_5_0");
			builder.put(grammarAccess.getContentDefinitionAccess().getImportsAssignment_5_1_1(), "rule__ContentDefinition__ImportsAssignment_5_1_1");
			builder.put(grammarAccess.getContentDefinitionAccess().getTypesAssignment_6_2(), "rule__ContentDefinition__TypesAssignment_6_2");
			builder.put(grammarAccess.getContentDefinitionAccess().getTypesAssignment_6_3_1(), "rule__ContentDefinition__TypesAssignment_6_3_1");
			builder.put(grammarAccess.getContentDefinitionAccess().getTemplatesAssignment_7_2(), "rule__ContentDefinition__TemplatesAssignment_7_2");
			builder.put(grammarAccess.getContentDefinitionAccess().getTemplatesAssignment_7_3_1(), "rule__ContentDefinition__TemplatesAssignment_7_3_1");
			builder.put(grammarAccess.getContentDefinitionAccess().getUnitAssignment_8(), "rule__ContentDefinition__UnitAssignment_8");
			builder.put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
			builder.put(grammarAccess.getTemplateDefAccess().getNameAssignment_2(), "rule__TemplateDef__NameAssignment_2");
			builder.put(grammarAccess.getTemplateDefAccess().getRowsAssignment_4_0(), "rule__TemplateDef__RowsAssignment_4_0");
			builder.put(grammarAccess.getTemplateDefAccess().getRowsAssignment_4_1_1(), "rule__TemplateDef__RowsAssignment_4_1_1");
			builder.put(grammarAccess.getContentUnitAccess().getNameAssignment_1(), "rule__ContentUnit__NameAssignment_1");
			builder.put(grammarAccess.getContentUnitAccess().getAuthorAssignment_2(), "rule__ContentUnit__AuthorAssignment_2");
			builder.put(grammarAccess.getContentUnitAccess().getTypeAssignment_3(), "rule__ContentUnit__TypeAssignment_3");
			builder.put(grammarAccess.getContentUnitAccess().getSectionsAssignment_5(), "rule__ContentUnit__SectionsAssignment_5");
			builder.put(grammarAccess.getContentUnitAccess().getSectionsAssignment_6_1(), "rule__ContentUnit__SectionsAssignment_6_1");
			builder.put(grammarAccess.getType_ImplAccess().getNameAssignment_2(), "rule__Type_Impl__NameAssignment_2");
			builder.put(grammarAccess.getRowAccess().getColumnsAssignment_3_0(), "rule__Row__ColumnsAssignment_3_0");
			builder.put(grammarAccess.getRowAccess().getColumnsAssignment_3_1_1(), "rule__Row__ColumnsAssignment_3_1_1");
			builder.put(grammarAccess.getRowAccess().getUsetemplateAssignment_4_1(), "rule__Row__UsetemplateAssignment_4_1");
			builder.put(grammarAccess.getColumnAccess().getWidthAssignment_3_1(), "rule__Column__WidthAssignment_3_1");
			builder.put(grammarAccess.getColumnAccess().getElementsAssignment_4_0(), "rule__Column__ElementsAssignment_4_0");
			builder.put(grammarAccess.getColumnAccess().getElementsAssignment_4_1_1(), "rule__Column__ElementsAssignment_4_1_1");
			builder.put(grammarAccess.getUseTemplateAccess().getTypetemplateAssignment_1(), "rule__UseTemplate__TypetemplateAssignment_1");
			builder.put(grammarAccess.getUseTemplateAccess().getTemplateelementsAssignment_2_1(), "rule__UseTemplate__TemplateelementsAssignment_2_1");
			builder.put(grammarAccess.getUseTemplateAccess().getTemplateelementsAssignment_2_2_1(), "rule__UseTemplate__TemplateelementsAssignment_2_2_1");
			builder.put(grammarAccess.getImageAccess().getUrlAssignment_3_1(), "rule__Image__UrlAssignment_3_1");
			builder.put(grammarAccess.getWidgetAccess().getNameAssignment_1(), "rule__Widget__NameAssignment_1");
			builder.put(grammarAccess.getWidgetAccess().getWidgettypeAssignment_3(), "rule__Widget__WidgettypeAssignment_3");
			builder.put(grammarAccess.getWidgetAccess().getWidgetelementsAssignment_4_1(), "rule__Widget__WidgetelementsAssignment_4_1");
			builder.put(grammarAccess.getWidgetAccess().getWidgetelementsAssignment_4_2_1(), "rule__Widget__WidgetelementsAssignment_4_2_1");
			builder.put(grammarAccess.getTextAccess().getHtmlAssignment_2_1(), "rule__Text__HtmlAssignment_2_1");
			builder.put(grammarAccess.getNumberAccess().getNumAssignment_2(), "rule__Number__NumAssignment_2");
			builder.put(grammarAccess.getLiteralAccess().getLiteralAssignment_2(), "rule__Literal__LiteralAssignment_2");
			builder.put(grammarAccess.getVideoAccess().getIdAssignment_3_1(), "rule__Video__IdAssignment_3_1");
			builder.put(grammarAccess.getVideoAccess().getTitleAssignment_5_1(), "rule__Video__TitleAssignment_5_1");
			builder.put(grammarAccess.getPlaceHolderAccess().getTypeAssignment_1(), "rule__PlaceHolder__TypeAssignment_1");
			builder.put(grammarAccess.getGameAccess().getIdAssignment_3_1(), "rule__Game__IdAssignment_3_1");
			builder.put(grammarAccess.getFieldValueAccess().getNameAssignment_0(), "rule__FieldValue__NameAssignment_0");
			builder.put(grammarAccess.getFieldValueAccess().getFieldvalueAssignment_2(), "rule__FieldValue__FieldvalueAssignment_2");
			builder.put(grammarAccess.getRecordValueAccess().getRecordvaluesAssignment_1(), "rule__RecordValue__RecordvaluesAssignment_1");
			builder.put(grammarAccess.getRecordValueAccess().getRecordvaluesAssignment_2_1(), "rule__RecordValue__RecordvaluesAssignment_2_1");
			builder.put(grammarAccess.getListValueAccess().getListvaluesAssignment_1(), "rule__ListValue__ListvaluesAssignment_1");
			builder.put(grammarAccess.getListValueAccess().getListvaluesAssignment_2_1(), "rule__ListValue__ListvaluesAssignment_2_1");
			builder.put(grammarAccess.getWidgetTypeAccess().getNameAssignment_2(), "rule__WidgetType__NameAssignment_2");
			builder.put(grammarAccess.getWidgetTypeAccess().getWidgettypeelementsAssignment_4(), "rule__WidgetType__WidgettypeelementsAssignment_4");
			builder.put(grammarAccess.getWidgetTypeAccess().getWidgettypeelementsAssignment_5_1(), "rule__WidgetType__WidgettypeelementsAssignment_5_1");
			builder.put(grammarAccess.getCompositeType_ImplAccess().getNameAssignment_2(), "rule__CompositeType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getSectionAccess().getNameAssignment_2(), "rule__Section__NameAssignment_2");
			builder.put(grammarAccess.getSectionAccess().getImageAssignment_4_1(), "rule__Section__ImageAssignment_4_1");
			builder.put(grammarAccess.getSectionAccess().getTitleAssignment_5_1(), "rule__Section__TitleAssignment_5_1");
			builder.put(grammarAccess.getSectionAccess().getTypeAssignment_6_1(), "rule__Section__TypeAssignment_6_1");
			builder.put(grammarAccess.getSectionAccess().getRowsAssignment_7_0(), "rule__Section__RowsAssignment_7_0");
			builder.put(grammarAccess.getSectionAccess().getRowsAssignment_7_1_1(), "rule__Section__RowsAssignment_7_1_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getNameAssignment_1(), "rule__SimpleType__NameAssignment_1");
			builder.put(grammarAccess.getRecordTypeAccess().getNameAssignment_0(), "rule__RecordType__NameAssignment_0");
			builder.put(grammarAccess.getRecordTypeAccess().getRecordtypeAssignment_2(), "rule__RecordType__RecordtypeAssignment_2");
			builder.put(grammarAccess.getRecordTypeAccess().getRecordtypeAssignment_3_1(), "rule__RecordType__RecordtypeAssignment_3_1");
			builder.put(grammarAccess.getFieldAccess().getNameAssignment_0(), "rule__Field__NameAssignment_0");
			builder.put(grammarAccess.getFieldAccess().getFieldtypeAssignment_2(), "rule__Field__FieldtypeAssignment_2");
			builder.put(grammarAccess.getListTypeAccess().getNameAssignment_0(), "rule__ListType__NameAssignment_0");
			builder.put(grammarAccess.getListTypeAccess().getListtypeAssignment_3(), "rule__ListType__ListtypeAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UpctformaGrammarAccess grammarAccess;

	@Override
	protected InternalUpctformaParser createParser() {
		InternalUpctformaParser result = new InternalUpctformaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UpctformaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UpctformaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
