/*
 /*
 * generated by Xtext 2.12.0
 */
package org.xtext.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import upctformaevalua.EvaluationUnit
import upctformaevalua.Question
import upctformaevalua.SingleAnswer
import upctformaevalua.MultipleAnswer
import upctformaevalua.TrueOrFalse
import upctformaevalua.Single
import upctformaevalua.Answer
import upctformaevalua.Multiple

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class UpctformaevaluaGenerator extends AbstractGenerator {
	var String fileindex = ''; 
	var String filejs = ''; 
	
	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		for (e : resource.allContents.toIterable.filter(EvaluationUnit)){
			compile(e,fsa)
		}
	}
		def writeCabeceraWithoutInteroperability(EvaluationUnit eu){'''
		<!DOCTYPE html>
		
		<html>
		<head>
			<meta charset="utf-8">
			<title>«eu.name»</title>
		
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/bootstrap/css/bootstrap.min.css" />
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/base.css" >
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/main.css" >
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/icomoon.css">
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/animate-custom.css" >
		
		 	<link rel="stylesheet" href="../../evaluationunit/font-awesome/css/fontawesome-all.min.css" media="screen" charset="utf-8">
		 		
			<link rel="icon" href="../../evaluationunit/img/favicon.png" type="image/png">
		</head>
		
		<body data-spy="scroll" data-offset="0" data-target="#navbar-main">
			
		<div id="navbar-main"> 
		  <!-- Fixed navbar -->
		  <div class="navbar navbar-inverse navbar-fixed-scroll" role="navigation">
		   
		 
		<header>
			<div id="cabecera">
				<h1 class="titulo text-white text-center">«eu.name»</h1>
			</div>
		</header>
		
		<!-- /headerwrap --> 
		<!-- ==== GREYWRAP ==== -->
		<div id="greywrap">
		<div class="container">
		  <div class="row white">			
				<div id="infoEvaluacion"></div>			
				<div id="encabezadoEvaluacion"></div>
			
		    <div id="preguntas">
	'''	
	}
	
	def writeCabecera(EvaluationUnit eu){'''
		<!DOCTYPE html>
		<?php
			$numero = count($_GET);
			$tags = array_keys($_GET);// obtiene los nombres de las varibles
			$valores = array_values($_GET);// obtiene los valores de las varibles
		
			require_once "../../../config.php";
		
			use \Tsugi\Util\LTI;
			use \Tsugi\Core\Settings;
			use \Tsugi\Core\LTIX;
			use \Tsugi\UI\SettingsForm;
		
			$LTI = LTIX::requireData();
			$p = $CFG->dbprefix;
			if (isset($_POST["points"])){
				//$points = json_decode($_POST["points"], true);
				$points = $_POST["points"];
				$tipo = "gamification";
				$identificador = $_POST["identificador"];
				$unidades = $_POST["unidades"];
			}else{
				$points = "";
				$tipo = "normal";
				$uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
				$identificador =  "https://". $_SERVER["HTTP_HOST"] . $uri_parts[0];
				$unidades = 0;
			}
		
			$context = $_SESSION['lti']['context_id'];
		?>
		
		<html>
		<head>
			<meta charset="utf-8">
			<title>«eu.name»</title>
		
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/bootstrap/css/bootstrap.min.css" />
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/base.css" >
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/main.css" >
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/icomoon.css">
			<link rel="stylesheet" type="text/css" href="../../evaluationunit/css/animate-custom.css" >
		
		 	<link rel="stylesheet" href="../../evaluationunit/font-awesome/css/fontawesome-all.min.css" media="screen" charset="utf-8">
		 		
			<link rel="icon" href="../../evaluationunit/img/favicon.png" type="image/png">
		</head>
		
		<body data-spy="scroll" data-offset="0" data-target="#navbar-main" unload="javascript:finUnidad();" onLoad="setInterval('keepAlive()',600000);">
			<script type="text/javascript">
				var link = '<?php echo $LINK->id; ?>';
				var title = '<?php echo $LINK->title; ?>';
				var usd = '<?php echo $USER->id; ?>';
				var displayname = '<?php echo $USER->displayname; ?>';
				var email = '<?php echo $USER->email; ?>';
				var firstname = '<?php echo $USER->firstname; ?>';
				var lastname = '<?php echo $USER->lastname; ?>';
				var session_id = '<?php echo session_id(); ?>';	
				var tipounit = '<?php echo $tipo; ?>';
				var points = '<?php echo $points; ?>';
				var unidades = '<?php echo $unidades; ?>';
				var identificador = '<?php echo $identificador; ?>';
				var context = '<?php echo $context; ?>';
			</script>
			
		<div id="navbar-main"> 
		  <!-- Fixed navbar -->
		  <div class="navbar navbar-inverse navbar-fixed-scroll" role="navigation">
		   
		 
		<header>
			<div id="cabecera">
				<h1 class="titulo text-white text-center">«eu.name»</h1>
			</div>
		</header>
		
		<!-- /headerwrap --> 
		<!-- ==== GREYWRAP ==== -->
		<div id="greywrap">
		<div class="container">
		  <div class="row white">			
				<div id="infoEvaluacion"></div>			
				<div id="encabezadoEvaluacion"></div>
			
		    <div id="preguntas">
	'''	
	}
	
	def writeFinalPie(){'''
				<script type="text/javascript">inicializar();</script>	
			</body>
		</html>		
	'''
	
	}
	def writePie(){'''
		</div>
			    <div class="clearfix"></div>
				<div class="col-md-4">  
			    	<p><a href="#" id="buttonSubmit" class="btn btn-primary" role="button">Submit</a></p>
			    </div>
			       
			    
			  </div>
			  <!-- row --> 
			  <div class="row">
			   <div class="col-md-12" id="resultados">RESULTADO</div>			     
			  </div>
			</div>
			<!-- container --> 
			</div>
		<footer id="footerwrap">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-3 indie_footer">
							<p><a href="https://twitter.com/indie_eu?lang=es" target="_blank"><i class="fab fa-twitter visto"></i></a></p>
							<p><a href="http://indie.upct.es/" target="_blank"><i class="fas fa-globe visto"></i></a></p>
							<p><i class="far fa-edit visto"></i> INDIe Project</p>
						</div>
						<div class="col-md-9 indie_footer">
						</div>
					</div>
					<br>	
				</div>
			</footer>
		
			<div class="modal fade" id="sharedModal" tabindex="-1" role="dialog" aria-labelledby="sharedModalLabel">
				<div class="modal-dialog" role="document">
					
				</div>
			</div>
			
		
			<!-- Placed at the end of the document so the pages load faster --> 
			<script type="text/javascript" src="../../evaluationunit/js/jquery-1.10.2.min.js"></script>
			<script type="text/javascript" src="../../evaluationunit/js/modernizr.custom.js"></script>
			<script type="text/javascript" src="../../evaluationunit/bootstrap/js/bootstrap.min.js"></script>
			<script type="text/javascript" src="evaluacion.js"></script>
			<script type="text/javascript" src="../../evaluationunit/js/funciones.js"></script>
			<script type="text/javascript" src="../../evaluationunit/js/progreso_mapa.js"></script>
			
	'''	
	}
	
	def compile(EvaluationUnit eu, IFileSystemAccess2 fsa){	
		fileindex = ''; 
		filejs = '';
		
		var pathcadena = fsa.getURI("").toFileString();
		if (pathcadena !== null){			
			if (pathcadena.contains("preview")){
				fileindex = fileindex + writeCabeceraWithoutInteroperability(eu).toString();
			}else{
				fileindex = fileindex + writeCabecera(eu).toString();	
			}
		}else{
			fileindex = fileindex + writeCabeceraWithoutInteroperability(eu).toString();
		}
		
		filejs = filejs +'''
			var respuestasEstudiante= new Array();
			var respuestascorrectas= new Array();
			var enunciados= new Array();
			var respuestas= new Array();
			var tipoPreguntas= new Array();
		 	function inicializarPreguntas(){
		'''
		var contadorpreguntas = 0;
		for (var x = 0; x < eu.questions.length; x++){			
			var q = eu.questions.get(x);
				
			if (q instanceof SingleAnswer){
				contadorpreguntas++;
				filejs = filejs +'''				
					tipoPreguntas[«contadorpreguntas»] = 0;	
					enunciados[«contadorpreguntas»] = new Array();
					enunciados[«contadorpreguntas»].push('«q.statements.text»');
					respuestas[«contadorpreguntas»] = new Array();
					respuestascorrectas[«contadorpreguntas»] = new Array();
					respuestascorrectas[«contadorpreguntas»].push(«q.correctanswer»);
					respuestasEstudiante[«contadorpreguntas»] = new Array();
				''';	
				fileindex = fileindex + '''
					<div class="col-md-6">
    					<div class="list-group" data-value="«contadorpreguntas»">
					        <p class="list-group-item-heading" id="enunciado«contadorpreguntas»" data-value="«contadorpreguntas»" >«q.statements.text»</br><span class="tipoPregunta"> (Single Answer)</span></p>
				'''.toString();
				for (var i = 0; i < q.answers.length; i++){
					var a = q.answers.get(i);				
					fileindex = fileindex + '''				
						        <a href="#" class="list-group-item respuesta" id="respuesta«contadorpreguntas»«i+1»" data-value="«i+1»">«a.text»</a>
					'''.toString();	
					filejs = filejs +'''
						respuestas[«contadorpreguntas»].push('«a.text»');
					'''.toString();									
				}
				fileindex = fileindex + '''
						    </div>
						    <div class="feedbackCorrecto alert alert-success" role="alert" id="feedbackCorrecto«contadorpreguntas»">Correct.</div>
						    <div class="feedbackIncorrecto alert alert-danger" role="alert" id="feedbackIncorrecto«contadorpreguntas»">Incorrect.</div>
						</div>
				'''.toString();
			}else if (q instanceof MultipleAnswer){
				contadorpreguntas++;
				val qt = q as MultipleAnswer
				fileindex = fileindex + '''
					<div class="col-md-6">
    					<div class="list-group" data-value="«contadorpreguntas»">
					        <p class="list-group-item-heading" id="enunciado«contadorpreguntas»" data-value="«contadorpreguntas»">«q.statements.text»</br><span class="tipoPregunta"> (Multiple Answer)</span></p>
				'''.toString();
				filejs = filejs +'''
					tipoPreguntas[«contadorpreguntas»] = 1;
					enunciados[«contadorpreguntas»] = new Array();
					enunciados[«contadorpreguntas»].push('«q.statements.text»');
					respuestas[«contadorpreguntas»] = new Array();
					respuestascorrectas[«contadorpreguntas»] = new Array();
					respuestasEstudiante[«contadorpreguntas»] = new Array();
				''';
				for (var i = 0; i < q.answers.length; i++){
					var a = q.answers.get(i);
					var at = q.answers.get(i) as Multiple;						
					
					filejs = filejs +'''
						respuestas[«contadorpreguntas»].push('«a.text»');
					'''.toString();
					
					if (a.value){
						filejs = filejs +'''
							respuestascorrectas[«contadorpreguntas»].push(«i+1»);
						''';
					}				
					fileindex = fileindex + '''				
						        <a href="#" class="list-group-item respuesta" id="respuesta«contadorpreguntas»«i+1»" data-value="«i+1»">«a.text»</a>
					'''.toString();					
				}
				fileindex = fileindex + '''
						    </div>
						    <div class="feedbackCorrecto alert alert-success" role="alert" id="feedbackCorrecto«contadorpreguntas»">Correct.</div>
						    <div class="feedbackIncorrecto alert alert-danger" role="alert" id="feedbackIncorrecto«contadorpreguntas»">Incorrect.</div>
						</div>
				'''.toString();
			}else if (q instanceof TrueOrFalse){
					for (var j = 0; j < q.assertions.length; j++){
						contadorpreguntas++;
						var aser = q.assertions.get(j);
						filejs = filejs +'''
							tipoPreguntas[«contadorpreguntas»] = 2;
							enunciados[«contadorpreguntas»] = new Array();
							enunciados[«contadorpreguntas»].push('«aser.text»');
							respuestas[«contadorpreguntas»] = new Array();
							respuestas[«contadorpreguntas»].push('True');
							respuestas[«contadorpreguntas»].push('False');
							respuestascorrectas[«contadorpreguntas»]= new Array();
							respuestasEstudiante[«contadorpreguntas»] = new Array();
						''';
						if (aser.value == true){
							filejs = filejs +'''
								respuestascorrectas[«contadorpreguntas»].push(1);
							''';
						}else{
							filejs = filejs +'''
								respuestascorrectas[«contadorpreguntas»].push(2);
							''';
						}	
						fileindex = fileindex + '''
							<div class="col-md-6">
		    					<div class="list-group" data-value="«contadorpreguntas»">
							        <p class="list-group-item-heading" id="enunciado«contadorpreguntas»" data-value="«contadorpreguntas»">«aser.text»</br><span class="tipoPregunta"> (True or False Question)</span></p>
						'''.toString();
						fileindex = fileindex + '''				
							        <a href="#" class="list-group-item respuesta" id="respuesta«contadorpreguntas»1" data-value="1">True</a>
							        <a href="#" class="list-group-item respuesta" id="respuesta«contadorpreguntas»2" data-value="2">False</a>
						'''.toString();
						fileindex = fileindex + '''
								    </div>
								    <div class="feedbackCorrecto alert alert-success" role="alert" id="feedbackCorrecto«contadorpreguntas»">Correct.</div>
								    <div class="feedbackIncorrecto alert alert-danger" role="alert" id="feedbackIncorrecto«contadorpreguntas»">Incorrect.</div>
								</div>
						'''.toString();
					}
				
			}
		}

		
		fileindex = fileindex + writePie().toString();

		if (pathcadena !== null){
			if (pathcadena.contains("preview")){
				fileindex = fileindex + '''
					<script>
					   	var sinConexionREST = 1;
					</script>
				'''
			}else{
				fileindex = fileindex + '''
					<script>
					   	var sinConexionREST = 0;
					</script>
				'''				
			}
		}else{
			fileindex = fileindex + '''
				<script>
				   	var sinConexionREST = 1;
				</script>
			'''
		}
						
		fileindex = fileindex + writeFinalPie().toString();
		
		filejs = filejs +'''
		 	}
		'''
		fsa.generateFile("index.php",fileindex)  
		fsa.generateFile("evaluacion.js",filejs)
	}
}
