/*
 * generated by Xtext 2.17.1
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.upctformaevalua.ui.internal.UpctformaevaluaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UpctformaevaluaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UpctformaevaluaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UpctformaevaluaActivator activator = UpctformaevaluaActivator.getInstance();
		return activator != null ? activator.getInjector(UpctformaevaluaActivator.ORG_XTEXT_UPCTFORMAEVALUA) : null;
	}

}
