/*
 * generated by Xtext 2.17.1
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUpctformaevaluaScopeProvider extends DelegatingScopeProvider {
}
